services:
 database:
    image: mysql:8.0.36
    container_name: database
    volumes:
    - ./server/mysql:/var/lib/mysql
    environment:
    - "MYSQL_DATABASE=app"
    - "MYSQL_USER=app"
    - "MYSQL_PASSWORD=app@"
    - "MYSQL_ROOT_PASSWORD=root@"
    ports:
    - "3306:3306"
